// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenConfigDir():Promise<void>;

export function OpenLogDir():Promise<void>;

export function Start():Promise<void>;

export function Status():Promise<Record<string, any>>;

export function Stop():Promise<void>;
