// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenConfigDir() {
  return window['go']['desktop']['Service']['OpenConfigDir']();
}

export function OpenLogDir() {
  return window['go']['desktop']['Service']['OpenLogDir']();
}

export function Start() {
  return window['go']['desktop']['Service']['Start']();
}

export function Status() {
  return window['go']['desktop']['Service']['Status']();
}

export function Stop() {
  return window['go']['desktop']['Service']['Stop']();
}
